### ISSUE TITLE
performance drop when using lora finetune

### ISSUE THREAD

**Issue by luodian873** [TIGER-AI-Lab/Mantis#10]
Thanks for your nice work.

I am training mantis-8b-siglip-llama3 with lora. However, it appears that there is a non-negligible performance drop when using lora finetuning. Two evaluation benchmark results are given here,

-| Mantis-Eval | NLVR2 |
--- | --- | --- |
report in paper | 59.45 | 87.43 |
lora results | 51.61 | 82.06 |

For pretraining and fine-tuning, I did not modify any training-specific hyperparameter. 

Perhaps it is caused by some errors when loading lora model during inference. I notice that you did lora finetuning in ablations. Can authors help on this? 

Thanks.

**Comment by wenhuchen** [comment]
The reported results in the main table is by full-finetuning. You are fine-tuning with Lora, the gap is expected? 
Yes, we only use Lora fine-tuning in ablation, but the main table is based on full-finetune.

**Comment by luodian873** [comment]
> The reported results in the main table is by full-finetuning. You are fine-tuning with Lora, the gap is expected? Yes, we only use Lora fine-tuning in ablation, but the main table is based on full-finetune.

Thanks for your kind feedback. I think I will go with full-finetune as aligned with main table in this paper.
