### ISSUE TITLE
How do you use lmms-eval to evaluate single-image, because i want to evaluate OCR ability with my finetuning model

### ISSUE THREAD

**Issue by BrenchCC** [TIGER-AI-Lab/Mantis#13]

**Comment by jdf-prog** [comment]
I have forked a previous lmmseval repo with mantis implementation. Please check it out. 

Also, LMMs-eval now seems to officially support Mantis, you can you directly use them!

**Comment by BrenchCC** [comment]
Thank you for your reply! The LMMS-Eval has supported Mantis, and I had tried it. By the way,I also push my PR for VLMEvalKit of OpenCompass to support Mantis. Maybe you can try it. Thanks!
