### ISSUE TITLE
Pretrain Image Data

### ISSUE THREAD

**Issue by srymaker** [TIGER-AI-Lab/Mantis#18]
Thanks for your great work!
I wanna know where can i find the image data in llava pretrain. Is this the same in Mantis-Instruct/
llava_665k_multi train_images.zip?

**Comment by wenhuchen** [comment]
I believe it's under https://huggingface.co/datasets/TIGER-Lab/llava-data.

**Comment by srymaker** [comment]
But in the https://huggingface.co/datasets/TIGER-Lab/llava-data there don‘t have the image file
