### ISSUE TITLE
Confusion about Eval and Instruct in README

### ISSUE THREAD

**Issue by emanuelevivoli** [TIGER-AI-Lab/Mantis#21]
Hello!
I'm a big fan of your Mantis paper, I really like it! (and thanks for this repo!)

I have a simple question, to clarify the reproducibility. In the README there is written:
> Intermediate Checkpoints
The following intermediate checkpoints after pre-training the multi-modal projectors are also available for experiment reproducibility (Please note the following checkpoints still `needs further fine-tuning on Mantis-Eval to be intelligent`. They are not working models.):
[TIGER-Lab/Mantis-8B-clip-llama3-pretraind](https://huggingface.co/TIGER-Lab/Mantis-8B-clip-llama3-pretraind)
[TIGER-Lab/Mantis-8B-siglip-llama3-pretraind](https://huggingface.co/TIGER-Lab/Mantis-8B-siglip-llama3-pretraind)

But I assume there is a mistake and it should be Mantis-Instruct, right?
<img width="677" alt="image" src="https://github.com/user-attachments/assets/5597c3a1-ed6e-40d2-87f3-f1064c228d45">

**Comment by jdf-prog** [comment]
Yeah, it's a typo. Thanks for pointing out and sorry for the late response. It should be Mantis-Instruct instead of Mantis-Eval. I now have fixed this typo!
