### ISSUE TITLE
Missing FUYU device_map fix for multi-GPU setups

### ISSUE THREAD

**Issue by ftoschi14** [TIGER-AI-Lab/Mantis#3]
### Issue Description
The FUYU model implementation currently lacks support for multi-GPU setups. This issue has already been addressed and fixed in Huggingface's transformers repository.

### Relevant Pull Request
Here's the link to the PR in the Hugging Face repository: https://github.com/huggingface/transformers/pull/29880

**Comment by jdf-prog** [comment]
Hi, I have updated the model according to the PR. Please checkout!
