### ISSUE TITLE
about conda env for finetuning

### ISSUE THREAD

**Issue by xing0047** [TIGER-AI-Lab/Mantis#8]
Nice work! Thanks for contribution.

We are carrying out instruction tuning experiments with `Mantis-8B-siglip-llama3`. The pretraining and instruction finetuning with lora work fine, except for full param finetuning. The warning below came up and finetuning got stuck. I put this here for others reference.

```
Invalidate trace cache @ step 344: expected module 345, but got module 1
```

Referring to the [issue](https://github.com/microsoft/DeepSpeed/discussions/4081), this might be due to how `accelerate` or `deepspeed` is installed. Noticing that there is no version specifications in `setup.py` from this repo, may we ask the exact versions you use for fine-tuning, for some dependencies like `torch`, `accelerate` or `deepspeed`?

Thanks in advance.

**Comment by emanuelevivoli** [comment]
I have got the same problem. Solved by uninstall deepspeed, downgrade numpy to v1.x, and install deepspeed again

**Comment by xing0047** [comment]
@emanuelevivoli Thanks for your kind reply. I will try this and see if it works for me.
