### ISSUE TITLE
Training only with Batch_size = 1 for Multimodal models

### ISSUE THREAD

**Issue by emanuelevivoli** [TIGER-AI-Lab/Mantis#9]
Hello! Thanks for open-sourcing the code :)
I'm playing a bit with the code and trying to replicate the pre-training and fine-tuning results, but I'm encountering many problems.

The problems I'm having can be represented in two groups:
- Datasets not well-formatted
- Processor problems with multi-image input

## 1. Datasets
The LLaVA pre-training script `mantis/train/scripts/pretrain_mllava.sh` uses the online hugging face dataset, but the majority of the data seems not present. In the `TIGER-Lab/llava-data` dataset, the `llava-pretrain` presents only 278670 images in 660 subfolders while the `llava-finetune` has only 348679 images across the folders "coco, gqa, ocr_vqa, textvqa, vg". Regarding the llava-finetune, for the majority of the images in the CC3M I'm getting:
```bash
[PosixPath('.cache/huggingface/datasets/TIGER-Lab___llava-data/llava_pretrain/0.0.0/73ecf20404b651edea601a8b868b2c818f3a7abf5fda24c2d8b0993118c3aea4/train_images/images/00266/002667434.jpg')] does not exist
Error at 100759
```

## 2. AssertionError

Regarding LLaVA fine-tuning, the script raise an error of unsupported multi-images input ("This method only supports a single input, but get 4 inputs"), which seems to come from the LLaVA processor method `_right_pad_inputs_with_attention_mask`. Why doesn't LLaVA support multi-input images? This error is raised both with `llava` and `mllava` for `mllava_type` in the setting, and using the CLIP version.

The idefics2 script seems to work with the default settings, downloading the data and starting the run (I'm using the `train_idefics2.sh` script, with default qlora finetuning). However, I have noticed that during training the memory usage of some GPUs (in my case the 0 and 2) spikes many times, going from 30% to 89%. I have tried to increase the `per_device_train_batch_size` to more than 1 (I have 40GB a100 GPU) but I'm getting strange errors that I didn't get in the original settings (the only change is `per_device_train_batch_size=4` in row 139):
```bash
Traceback (most recent call last):
  File "Mantis/mantis/train/train_idefics2.py", line 255, in <module>
    main(training_args, data_args, model_args)
  File "Mantis/mantis/train/train_idefics2.py", line 229, in main
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "miniconda3/envs/mantis/lib/python3.10/site-packages/transformers/trainer.py", line 1876, in train
    return inner_training_loop(
  File "miniconda3/envs/mantis/lib/python3.10/site-packages/transformers/trainer.py", line 2178, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "miniconda3/envs/mantis/lib/python3.10/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File ".local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File ".local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File ".local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File ".local/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File ".local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File ".local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "Mantis/mantis/train/data.py", line 753, in __call__
    batch_encoding = self._right_pad_inputs_with_attention_mask(model_inputs=batch)
  File "Mantis/mantis/train/data.py", line 741, in _right_pad_inputs_with_attention_mask
    assert len(model_inputs) == 1, "This method only supports a single input, but get {} inputs".format(len(model_inputs))
AssertionError: This method only supports a single input, but get 4 inputs
```
This error seems related to the one I had with LLaVA which makes me thinking that probably we should modify/create a `_right_pad_inputs_with_attention_mask` method for the idefict2 processor, as well as for llava, similar to the one made for MFuyu ?

Please, give some advice

**Comment by emanuelevivoli** [comment]
Hello again @jdf-prog !

I admit that my understanding of all the repository elements is limited but I see that the error I'm having is due to the batch_size: in your context, all models (apart from fuyu and idefics2, I guess) only support single batch training, checking if the `len(model_inputs) == 1`. 

Why is this the case?

**Comment by jdf-prog** [comment]
@emanuelevivoli Thanks for the question.

1. For the dataset's missing images, I have encountered this error before, I have also encounter similar errors before. And it turns out that it's likely you kill the zip decompressing process before it finished, so some of the images are missing. I think you should try delete previous downloaded images and try downloading again from scratch.

2. For the second problem, you should set `per_device_batch_size=1`, as when I was writing the code, I found that support mini batch training is kind of complicated and always encounter some unknown errors. To avoid this, I simply set it to 1 and add this assert clause. It's reasonable because when `per_device_batch_size=1`, the gpu memory occupation is already pretty high, so increasing this parameters will usually cause OOM. Try increase `gradient_accumulation_steps` to increase the global batch size.

**Comment by emanuelevivoli** [comment]
Thank you so much for the answer! I'll do as you suggested for the data, I hope it will solve it.

Regarding the batch size = 1, I understand that it is just fine, but I'm asking so because I'm planning to run on 80GB GPUs and I'm not using all of them... Thank you so much anyway.

**Comment by gordonhu608** [comment]
I don't think I killed zip decompressing process before it finished. And I tried delete previous downloaded images and try downloading again from scratch but still got the image not exist error. Any suggestions on how to approach this? and maybe a little docs for how to directly use offline data config file would be very helpful, too (which seems to me is easier). Thanks !

**Comment by jdf-prog** [comment]
Hi @gordonhu608, I have added example training scrtipts for various data formats (text-image, text-video, classification) in the [readme](https://github.com/TIGER-AI-Lab/Mantis?tab=readme-ov-file#training-examples-with-different-data-formats). And the data are all pre-prepared so you don't need to download the data. You can use these scripts for debugging.

**Comment by gordonhu608** [comment]
Excellent! Thank you!
